
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
server:
  port: 1117

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:opure/config-server.git
          search-paths: config-server/config-repo
